### ISSUE TITLE
How can I solve this problem?

### ISSUE THREAD

**Issue by cjltw** [DiKorsch/l1_parts#1]
when I use 01_install.sh, I get a problem. How can I solve it?

Building experiment
Step 1/14 : FROM dikorsch/chainer-cuda101-opencv4.1.1
ERROR: Service 'experiment' failed to build: manifest for dikorsch/chainer-cuda101-opencv4.1.1:latest not found: manifest unknown: manifest unknown

**Comment by DiKorsch** [comment]
Hi, 

please checkout the "gcpr2019submission" tag. This should be the most stable version. The master branch is my current working branch and may have some issues.

Alternatively, you can build the mentioned image with `docker build -f Dockerfile2 --tag dikorsch/chainer-cuda101-opencv4.1.1 .`
